### Site metadata ###

site_name: DBPlus documentation
site_description: DBPlus documentation with examples
site_url: https://klaasbrant.github.io/DBPlus/

repo_url: https://github.com/klaasbrant/DBPlus
edit_uri: edit/master/docs/docs

### Build settings ###

theme: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Connecting: connecting.md
  - Querying Data: queries.md
  - Executing Statements: executing.md
  - Record & RecordCollection: records.md
  - QueryStore: querystore.md
  - CSV Import/Export: csv.md
  - Database Drivers: drivers.md